## Python Decorators

In [204]:
## Function that takes another function as argument and returns another function


def plus_one(f):
    # A decorator that adds 1
    def new_func(x):
        print("I'm adding 1 now...")
        return f(x) + 1
    return new_func


def times_two(f):
    # A decorator that multiplies by 2
    def new_func(x):
        print("I'm multiplying by 2 now ")      
        return f(x) * 2
    return new_func

# A decorated function

@plus_one
@times_two
def foo(x):
    return int(x)


foo(13)

I'm adding 1 now...
I'm multiplying by 2 now 


27

In [200]:
def loud(f):
    def new_func(*args, **kw):
        print('Calling with {} and {}'.format(args, kw))
        rtn = f(*args, **kw)
        print('Return value is {}'.format(rtn))
        return rtn
    return new_func

louder = loud(len)
numbr = louder([10,25,38])
print(louder)

Calling with ([10, 25, 38],) and {}
Return value is 3
<function loud.<locals>.new_func at 0x10588e048>


# # URLparse

In [131]:
from contextlib import closing
from urllib.parse import urlparse

vurl = "https://www.youtube.com/watch?v=x3nvbzSm4GU&list=RDx3nvbzSm4GU&spfreload=10#t=5"

def validate_url(vidlix_url):
        """ Validate that the link is valid Youtube URL """
        error = None
        vidlixer = urlparse(vidlix_url)
        if vidlixer.netloc != 'www.youtube.com':
            error = 'Only Youtube link are accepted for now'
        elif vidlixer.scheme != 'http' or 'https':
            error = "please include 'http://' or 'https://' in your link"
        return error

vidlix = urlparse(vurl)

print(vidlix)



ParseResult(scheme='https', netloc='www.youtube.com', path='/watch', params='', query='v=x3nvbzSm4GU&list=RDx3nvbzSm4GU&spfreload=10', fragment='t=5')


##Using the sys module

In [165]:
import sys


print(sys.platform)
print()
print(sys.version)
print()
print(sys.version_info)


darwin

3.4.3 |Anaconda 2.2.0 (x86_64)| (default, Mar  6 2015, 12:07:41) 
[GCC 4.2.1 (Apple Inc. build 5577)]

sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)


## Using the os module

In [176]:
import os

print(os.getcwd() )

print()
print(os.listdir() )

print()
print(os.path.split("/Users/RichardAfolabi/myGitHub/Programming Python 4th Edtn.ipynb"))

print()
print(os.path.isfile("/Users/RichardAfolabi/myGitHub/Programming Python 4th Edtn.ipynb"))

print()
print(os.path.abspath("/Users/RichardAfolabi/myGitHub/Programming Python 4th Edtn.ipynb"))

print()
print(os.path.dirname("/Users/RichardAfolabi/myGitHub/Programming Python 4th Edtn.ipynb"))

print()
print(os.path.basename("/Users/RichardAfolabi/myGitHub/Programming Python 4th Edtn.ipynb"))

print()
print(os.path.splitext("/Users/RichardAfolabi/myGitHub/Programming Python 4th Edtn.ipynb"))

print()
print(os.path.expanduser("/Users/RichardAfolabi/myGitHub/Programming Python 4th Edtn.ipynb"))

/Users/RichardAfolabi/myGitHub

['.DS_Store', '.ipynb_checkpoints', 'Data_Analysis_with_Python', 'DataScience_Materials', 'Flask Web Frameworks Playground.ipynb', 'flask-oauth-example', 'flasky', 'Mining_Social_Network_Data', 'oreilly-intro-to-flask-video', 'Programming Python 4th Edtn.ipynb', 'Python_Web_Programming', 'Scientific-Python', 'Templates']

('/Users/RichardAfolabi/myGitHub', 'Programming Python 4th Edtn.ipynb')

True

/Users/RichardAfolabi/myGitHub/Programming Python 4th Edtn.ipynb

/Users/RichardAfolabi/myGitHub

Programming Python 4th Edtn.ipynb

('/Users/RichardAfolabi/myGitHub/Programming Python 4th Edtn', '.ipynb')

/Users/RichardAfolabi/myGitHub/Programming Python 4th Edtn.ipynb


In [1]:
from datetime import datetime

mydate = datetime.utcnow()

print(mydate.strftime("%d %b, %Y"))

23 Apr, 2015


In [34]:
from enum import Enum

categories = Enum('Categories','Fun Family Comedy Animations Politics')


for cat in categories:
    print(cat)
    
    

    
category = 'fun, comedy, animations'

[cat.strip() for cat in category.split(',')]


bob = {'name': {'first': 'Bob', 'last': 'Smith'}, 
        'age': 42,
        'job': ['software', 'writing'], 
        'pay': (40000, 50000)
       }



Categories.Fun
Categories.Family
Categories.Comedy
Categories.Animations
Categories.Politics
{'last': 'Smith', 'first': 'Bob'}


## Masking & Fancy Slicing

In [85]:
import numpy as np


ar = np.random.rand(5)

print(ar)

mask = ar > 0.5

print(ar[mask])



ar3 = np.arange(36).reshape((6,6))
print(ar3)

# Select all elements from row 3 to end and cols 0, 2, and 5.
print('\n\n', ar3[3:,[0,2,5]])


# select all elements greater than 15

mask = ar3 > 15
print('\n\n', ar3[mask].reshape(2,10))


[ 0.94978612  0.42026056  0.61720658  0.68778524  0.4611995 ]
[ 0.94978612  0.61720658  0.68778524]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


 [[18 20 23]
 [24 26 29]
 [30 32 35]]


 [[16 17 18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33 34 35]]
